.TH CHANGE-UI 1 "January 2025" "Version 1.0" "change-ui Manual"
.SH NAME
change-ui \- A tool to change UI settings.

.SH SYNOPSIS
.B change-ui
[options]

.SH DESCRIPTION
change-ui is a command-line tool to modify user interface settings.

.SH OPTIONS
None.

.SH AUTHOR
Written by User <admin@openyellowos.com>.

